#!/usr/bin/env python3
"""
Build-time generator (dev-only; NOT run in the Cloud Run image) for the
ECONSTELLAR v5 control-operator calibration fixture.

It imports the FRONTIERS V.2 simulation module (the source of truth) and dumps
the M3-faithful calibrated plant plus the exact V.2 hyperparameters into
`v5_control_plant.json`, which the engine's control runners read to reproduce
the V.2 results.json golden values bit-for-bit. The plant is genuine derived
data: deterministically calibrated from the real MST panel by the published
V.2 pipeline (seed 20260618). Provenance is stamped into the fixture.

Run:  python3 export_v5_fixture.py
"""
import json, os, sys, hashlib

V2_SIM = ("/home/ecolex/versiondevs/ivy-fineco/papers/frontiers-v/"
          "V2-recursive-control/sim")
sys.path.insert(0, V2_SIM)
import numpy as np
import frontiers_v2_recursive as v2   # the V.2 source of truth

def main():
    # Reproduce the V.2 calibration exactly (same data, same maps, same seed-free
    # deterministic pipeline as v2.main()).
    dates, Z, names = v2.load_panel()
    Xw = v2.window_slice(dates, Z, *v2.WINDOWS["GFC"])
    Phi_gfc, _, _ = v2.ols_phi_ridge(Xw, v2.RIDGE_FRAC)
    rec = v2.recover_from_phi(Phi_gfc)
    cal = v2.calibrate_from_crisis(rec["B"], rec["eta"], rec["rB"],
                                   keep_frac=v2.KEEP_FRAC)
    G = cal["G"]
    fixture = {
        "_provenance": (
            "M3-faithful calibrated plant of FRONTIERS V.2 RECURSIVE CONTROL, "
            "derived from papers/contagion-channels/MST-contagion/Returns_prices.csv "
            "(26 assets, 2007-01-02..2025-11-27) by the published V.2 pipeline "
            "(GFC-window VAR(1) ridge-OLS -> recover B -> symmetric excitatory "
            "support -> keep top 30% edges -> scale to the crisis cascade root). "
            "Generated by r/fixtures/export_v5_fixture.py; numbers match "
            "papers/frontiers-v/V2-recursive-control/sim/results.json."),
        "asset_names": names,
        "n": int(G.shape[0]),
        "eta_cal": float(cal["eta"]),
        "lam_max_g": float(cal["lam_max_gtilde"]),
        "rB_cal": float(cal["rB_calibrated"]),
        "n_edges": int(cal["n_edges"]),
        "G_cal": [[float(x) for x in row] for row in G],
        # exact V.2 hyperparameters (the runners must use these verbatim)
        "hyper": {
            "beta_planner": v2.BETA_PLANNER,      # 0.95
            "beta_cascade": v2.BETA_CASCADE,      # 0.80
            "drift_lq": v2.DRIFT_LQ,              # 2.475
            "R_weight": 1.0, "Q_ctrl": 1.0,       # LQ cost weights (I, I)
            "safe": 0.80,                          # V.1 threshold-rule safe level
            "eta_grid": {"lo": 0.70, "hi": 1.05, "n": 141},
            "u_grid": {"lo": -0.10, "hi": 0.10, "n": 81},
            "c_adj": 50.0, "shock_sd": 0.010,      # value-iteration adjustment cost + shock
            "vi_tol": 1e-9, "vi_max_iter": 4000,
            "gh_nodes": 7,                          # Gauss-Hermite shock discretisation
        },
    }
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "v5_control_plant.json")
    with open(out, "w") as f:
        json.dump(fixture, f, indent=2)
    blob = json.dumps(fixture, sort_keys=True).encode()
    print("wrote", out)
    print("  n =", fixture["n"], " eta_cal =", round(fixture["eta_cal"], 6),
          " lam_max =", round(fixture["lam_max_g"], 6),
          " rB =", round(fixture["rB_cal"], 6), " edges =", fixture["n_edges"])
    print("  sha256 =", hashlib.sha256(blob).hexdigest()[:16])

if __name__ == "__main__":
    main()
